# Generated by Django 3.0.6 on 2020-06-10 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200610_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'get_latest_by': ['-date']},
        ),
    ]
